name: Learn Go with tests CI pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' 

      - name: Install dependencies
        run: go mod tidy

      - name: Run gofmt
        run: |
          fmt_files=$(gofmt -l .)
          if [ -n "$fmt_files" ]; then
            echo "The following files are not properly formatted:"
            echo "$fmt_files"
            exit 1
          fi

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          args: --timeout=5m

      - name: Run tests
        run: |
          go test -v ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out
